### ISSUE TITLE
Still work?

### ISSUE THREAD

**Issue by wibuf** [Quackster/Icarus#5]
Hey Quackster, I was looking for something like this I could modify for a small private server. Can you tell me if the release on the release page still works? I pulled it down, got the db setup, and the output log says: [ICARUS] >> Server is listening on 127.0.0.1:30000

However, I open that in a browser and the page never loads. Am I missing something?

**Comment by Quackster** [comment]
This project isn't a HTTP server. You make the Habbo client connect the IP:PORT it shows on the output. 

It's not a URL.
